[package]
name = "cargobomb"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[profile.dev]
opt-level = 0

[dependencies]
arc-cell = "0.1.5"
chrono = "0.3"
clap = "2.11.3"
crates-index = "0.9"
error-chain = "0.10"
flate2 = "0.2.9"
futures = "0.1.13"
futures-cpupool = "0.1.5"
kernel32-sys = "0.2.2"
lazy_static = "0.2"
libc = "0.2.7"
nix = "0.8.1"
rand = "0.3"
ref_slice = "1.1.1"
reqwest = "0.6"
result = "0.0.1"
scopeguard = "0.3"
semver = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slog = "2"
slog-scope = "3"
slog-term = "2"
tar = "0.4.0"
tempdir = "0.3.4"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-process = "0.1.2"
tokio-timer = "0.1.1"
toml = "0.2.1"
url = "1.1"
walkdir = "0.1.8"
winapi = "0.2.8"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
optional = false

[replace]
# Use mio from master until there is a new release.
# https://github.com/carllerche/mio/pull/605
# Otherwise, creating a bnuch of `tokio_core::reactor::Core`s leaks FDs.
"mio:0.6.7" = { git = "https://github.com/carllerche/mio/", branch = "master" }
